### ISSUE TITLE
integration will stop working in version 2021.6

### ISSUE THREAD

**Issue by robUx4** [h4/LYWSD02-home-assistant#19]
Here is the log I get when I load it in 2021.5

>2021-05-13 15:31:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration lywsd02_sensor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-13 15:31:48 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'lywsd02_sensor'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'lywsd02_sensor'

Also it seems the format of the documentation for the configuration doesn't work. It gives an error on the line
```    - platform: template```

**Comment by robUx4** [comment]
The template for the sensor now looks like this 
```yaml
template:
  - sensor:
      - name: Temp Salon
        unit_of_measurement: "°C"
        state: "{{ state_attr('sensor.my_thermometer', 'temperature')|float }}"
        device_class: temperature
        unique_id: lywsd02.d109.temp
```
